
version: '3.4'
services:
  myapp:
    container_name: my-app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PORT = ${PORT}
    ports:
      - 3001:${PORT}
    env_file:
      - .env
    volumes:
      - ./:/app
      - ignore:/app/node_modules/
volumes:
  ignore: